services:
  server:
    build: ./server
    container_name: fintrack_server
    ports:
      - "4000:4000"
    env_file:
      - ./.env.docker
    depends_on:
      - postgres
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    command: npm run dev -- --poll
  
  client:
    build: ./client
    container_name: fintrack_client
    ports:
      - "5173:5173"
    env_file:
      - ./.env.docker
    depends_on:
      - server
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173

  postgres:
    image: postgres:16
    container_name: fintrack_postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  server_node_modules:
  client_node_modules:
